language: python
sudo: false
python:
    - "3.5"

install:
    #------------------
    # Base requirements
    #------------------
#    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -f -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda config --prepend channels conda-forge
    - conda config --append channels digitalglobe # for rasterio v 1.0a9
    - conda config --append channels ioos # for rasterio v 1.0a2
    - bash setup_env.sh
    - source activate shakemap
    #---------------------
    # Install shakemap
    #---------------------
    - python setup.py install
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - py.test --cov=shakemap
    - echo `sphinx-build --version`
    #- flake8 shakemap
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
