language: python
sudo: false
python:
    - "3.6"

install:
    # Install shakemap and requirements
    - bash install.sh
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda activate shakemap
    - conda list
    - which gcc
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - py.test --cov=.
    - echo `sphinx-build --version`
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
