name: shakemap
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- affine=2.1.0
- alabaster=0.7.10
- appnope=0.1.0
- asn1crypto=0.22.0
- astroid=1.5.3
- attrs=17.3.0
- babel=2.5.1
- basemap=1.1.0
- beautifulsoup4=4.6.0
- bleach=2.0.0
- bokeh=0.12.13
- boost=1.65.1
- boost-cpp=1.65.1
- boto3=1.4.7
- botocore=1.5.92
- bzip2=1.0.6
- ca-certificates=2017.11.5
- cairo=1.14.6
- cartopy=0.15.1
- certifi=2017.11.5
- cffi=1.11.2
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- cloudpickle=0.4.0
- codecov=2.0.9
- commonmark=0.7.3
- coverage=4.4.2
- cryptography=2.1.4
- curl=7.55.1
- cycler=0.10.0
- dask=0.16.0
- dask-core=0.16.0
- decorator=4.1.2
- descartes=1.1.0
- distributed=1.20.2
- docutils=0.14
- entrypoints=0.2.3
- et_xmlfile=1.0.1
- expat=2.1.0
- fiona=1.7.10
- fontconfig=2.12.1
- freetype=2.7
- freexl=1.0.4
- future=0.16.0
- gdal=2.1.4
- geojson=2.0.0
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.51.4
- h5py=2.7.1
- hdf4=4.2.13
- hdf5=1.10.1
- heapdict=1.0.0
- html5lib=0.999999999
- icu=58.2
- idna=2.6
- imageio=2.2.0
- imagesize=0.7.1
- ipykernel=4.7.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.0.5
- isort=4.2.15
- jdcal=1.3
- jedi=0.10.2
- jinja2=2.10
- jmespath=0.9.3
- jpeg=9b
- json-c=0.12.1
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.1.0
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- kealib=1.4.7
- krb5=1.14.2
- lazy-object-proxy=1.3.1
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.1.4
- libgfortran=3.0.0
- libiconv=1.15
- libkml=1.3.0
- libnetcdf=4.4.1.1
- libpng=1.6.28
- libpq=9.6.3
- libsodium=1.0.15
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.7
- libxml2=2.9.5
- libxslt=1.1.32
- locket=0.2.0
- lxml=4.1.1
- markupsafe=1.0
- matplotlib=1.5.3
- mccabe=0.6.1
- mistune=0.8.3
- mock=2.0.0
- msgpack-python=0.4.8
- munch=2.2.0
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- networkx=1.11
- nose=1.3.7
- notebook=5.2.2
- numexpr=2.6.2
- numpydoc=0.7.0
- obspy=1.0.3
- olefile=0.44
- openjpeg=2.1.2
- openpyxl=2.5.0a2
- openssl=1.0.2n
- owslib=0.15.0
- pandas=0.21.0
- pandoc=2.0.4
- pandocfilters=1.4.1
- paramiko=2.3.1
- partd=0.3.8
- patsy=0.4.1
- pbr=3.1.1
- pcre=8.39
- pexpect=4.3.0
- pickleshare=0.7.4
- pillow=4.3.0
- pip=9.0.1
- pixman=0.34.0
- poppler=0.61.1
- poppler-data=0.4.8
- proj4=4.9.3
- prompt_toolkit=1.0.15
- psutil=5.4.0
- ptyprocess=0.5.2
- py=1.5.2
- pyasn1=0.3.7
- pycodestyle=2.3.1
- pycparser=2.18
- pycrypto=2.6.1
- pyepsg=0.3.2
- pyflakes=1.6.0
- pygments=2.2.0
- pylint=1.7.1
- pynacl=1.1.2
- pyopenssl=17.4.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pyshp=1.2.10
- pysocks=1.6.7
- pytest=3.2.5
- pytest-cov=2.5.1
- python=3.5.4
- python-dateutil=2.6.1
- python.app=1.2
- pytz=2017.3
- pywavelets=0.5.2
- pyyaml=3.12
- pyzmq=16.0.2
- qt=5.6.2
- qtawesome=0.4.4
- qtconsole=4.3.1
- qtpy=1.3.1
- rasterio=0.36.0
- readline=6.2
- requests=2.18.4
- rope=0.10.7
- s3transfer=0.1.11
- scikit-image=0.13.0
- seaborn=0.8.1
- setuptools=38.2.4
- shapely=1.6.2
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snowballstemmer=1.2.1
- snuggs=1.4.1
- sortedcontainers=1.5.7
- sphinx=1.6.5
- sphinxcontrib-websupport=1.0.1
- spyder=3.2.4
- sqlalchemy=1.1.13
- sqlite=3.13.0
- statsmodels=0.8.0
- tblib=1.3.2
- terminado=0.8.1
- testpath=0.3.1
- tk=8.5.19
- toolz=0.8.2
- tornado=4.5.2
- traitlets=4.3.2
- typing=3.6.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.0.8
- wrapt=1.10.11
- xerces-c=3.2.0
- xlrd=1.0.0
- xlsxwriter=0.9.8
- xlwt=1.2.0
- xz=5.2.3
- yaml=0.1.7
- zeromq=4.2.1
- zict=0.1.3
- zlib=1.2.11
- bcrypt=3.1.4
- configobj=5.0.6
- intel-openmp=2018.0.0
- mkl=2017.0.4
- numpy=1.13.1
- scipy=0.19.1
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - sphinx-argparse==0.2.1
  - ./impact-utils.zip
  - ./libcomcat.zip
  - ./mapio.zip
prefix: /Users/mhearne/anaconda3/envs/shakemap

