name: shakemap
channels:
  - conda-forge
  - defaults
  - digitalglobe
  - ioos
dependencies:
  - affine=2.2.0
  - alabaster=0.7.10
  - amptools=1.0.3
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - atomicwrites=1.1.5
  - attrs=18.1.0
  - babel=2.5.3
  - backcall=0.1.0
  - basemap=1.1.0
  - beautifulsoup4=4.6.0
  - blas=1.1
  - bleach=2.1.3
  - boto3=1.7.26
  - botocore=1.10.26
  - ca-certificates=2018.4.16
  - cartopy=0.16.0
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - coverage=4.5.1
  - cryptography=2.2.1
  - curl=7.60.0
  - cycler=0.10.0
  - dask-core=0.17.5
  - decorator=4.3.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - django=2.0.5
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fiona=1.7.11
  - freetype=2.6.3
  - freexl=1.0.5
  - future=0.16.0
  - gdal=2.1.4
  - geos=3.6.2
  - geotiff=1.4.2
  - giflib=5.1.4
  - h5py=2.8.0
  - hdf4=4.2.13
  - hdf5=1.10.1
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - imageio=2.3.0
  - imagesize=1.0.0
  - impactutils=0.8.4
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jdcal=1.4
  - jedi=0.12.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - json-c=0.12.1
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kealib=1.4.7
  - krb5=1.14.6
  - libcomcat=1.2.4
  - libdap4=3.18.3
  - libffi=3.2.1
  - libgdal=2.1.4
  - libgfortran=3.0.0
  - libiconv=1.15
  - libnetcdf=4.4.1.1
  - libpng=1.6.34
  - libpq=9.6.3
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lockfile=0.12.2
  - lxml=4.2.1
  - mapio=0.7.8
  - markupsafe=1.0
  - matplotlib=2.0.0rc2
  - mistune=0.8.3
  - mock=2.0.0
  - more-itertools=4.1.0
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=5.9
  - networkx=2.1
  - notebook=5.5.0
  - numexpr=2.6.5
  - numpy=1.12.1
  - obspy=1.1.0
  - olefile=0.45.1
  - openblas=0.2.20
  - openjpeg=2.1.2
  - openpyxl=2.5.3
  - openquake.engine=2.9.0
  - openssl=1.0.2o
  - owslib=0.16.0
  - packaging=17.1
  - pandas=0.23.0
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - paramiko=2.4.1
  - parso=0.2.1
  - pbr=4.0.3
  - pcre=8.39
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pillow=4.0.0
  - pip=9.0.3
  - pluggy=0.6.0
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - ps2ff=v1.2
  - psutil=5.4.5
  - ptyprocess=0.5.2
  - py=1.5.3
  - pyasn1=0.4.2
  - pycparser=2.18
  - pycrypto=2.6.1
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pynacl=1.1.2
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyshp=1.2.12
  - pysocks=1.6.8
  - pytest=3.6.0
  - pytest-cov=2.5.1
  - python=3.5.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pywavelets=0.5.2
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.6.2
  - qtconsole=4.3.1
  - rasterio=0.36.0
  - readline=7.0
  - requests=2.18.4
  - s3transfer=0.1.13
  - scikit-image=0.13.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=39.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - snowballstemmer=1.2.1
  - snuggs=1.4.1
  - sphinx=1.7.4
  - sphinxcontrib-websupport=1.0.1
  - sqlalchemy=1.2.7
  - sqlite=3.20.1
  - strec=2.0.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.22
  - versioneer=0.18
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - xerces-c=3.2.0
  - xlrd=1.1.0
  - xlsxwriter=1.0.4
  - xlwt=1.3.0
  - xz=5.2.3
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - bcrypt=3.1.4
  - configobj=5.0.6
  - python-daemon=2.1.2
