name: shakemap
channels:
- conda-forge
- defaults
dependencies:
- amptools
- basemap
- cartopy
- configobj
- defusedxml
- descartes
- docutils
- fiona
- gdal
- h5py
- impactutils
- libcomcat
- lockfile
- mapio
- matplotlib
- numexpr
- numpy
- obspy
- openquake.engine
- pandas
- ps2ff
- psutil
- pyproj
- pytest
- pytest-cov
- python=3.5
- python-daemon
- scikit-image
- scipy
- shapely
- strec
- versioneer
- kealib=1.4.7
