name: shakemap
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- affine=2.1.0=py_1
- alabaster=0.7.10=py35_1
- asn1crypto=0.22.0=py35_0
- astroid=1.5.3=py35_0
- attrs=17.3.0=py_0
- babel=2.5.1=py35_0
- basemap=1.1.0=py35_3
- beautifulsoup4=4.6.0=py35_0
- blas=1.1=openblas
- bleach=2.0.0=py35_0
- boost=1.65.1=py35_0
- boost-cpp=1.65.1=1
- boto3=1.4.7=py35_0
- botocore=1.5.92=py35_0
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- cairo=1.14.6=5
- cartopy=0.15.1=py35_5
- certifi=2017.11.5=py35_0
- cffi=1.11.2=py35_0
- chardet=3.0.4=py35_0
- click=6.7=py35_0
- click-plugins=1.0.3=py35_0
- cligj=0.4.0=py35_0
- coverage=4.4.2=py35_0
- cryptography=2.1.4=py35_0
- curl=7.55.1=0
- cycler=0.10.0=py35_0
- dask-core=0.16.0=py_0
- decorator=4.1.2=py35_0
- descartes=1.1.0=py35_0
- docutils=0.14=py35_0
- entrypoints=0.2.3=py35_1
- et_xmlfile=1.0.1=py35_0
- expat=2.1.0=3
- fiona=1.7.10=py35_2
- fontconfig=2.12.1=6
- freetype=2.7=2
- freexl=1.0.4=0
- future=0.16.0=py35_0
- gdal=2.1.4=py35_2
- geojson=2.0.0=py35_0
- geos=3.6.2=1
- geotiff=1.4.2=0
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- graphite2=1.3.10=0
- h5py=2.7.1=py35_2
- harfbuzz=1.4.3=0
- hdf4=4.2.13=0
- hdf5=1.10.1=1
- html5lib=0.999999999=py35_0
- icu=58.2=0
- idna=2.6=py35_1
- imageio=2.2.0=py35_0
- imagesize=0.7.1=py35_0
- ipykernel=4.7.0=py35_0
- ipython=6.2.1=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=7.0.5=py35_0
- isort=4.2.15=py35_0
- jdcal=1.3=py35_0
- jedi=0.10.2=py35_0
- jinja2=2.10=py35_0
- jmespath=0.9.3=py35_0
- jpeg=9b=2
- json-c=0.12.1=0
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_console=5.2.0=py35_0
- jupyter_core=4.4.0=py_0
- kealib=1.4.7=4
- krb5=1.14.2=0
- lazy-object-proxy=1.3.1=py35_0
- libdap4=3.18.3=2
- libffi=3.2.1=3
- libgdal=2.1.4=8
- libiconv=1.15=0
- libkml=1.3.0=4
- libnetcdf=4.4.1.1=10
- libpng=1.6.28=2
- libpq=9.6.3=0
- libsodium=1.0.15=1
- libspatialite=4.3.0a=18
- libssh2=1.8.0=2
- libtiff=4.0.7=1
- libxml2=2.9.5=2
- libxslt=1.1.32=0
- lxml=4.1.1=py35_0
- markupsafe=1.0=py35_0
- matplotlib=1.5.3=np113py35_8
- mccabe=0.6.1=py35_0
- mistune=0.8.3=py_0
- munch=2.2.0=py35_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- networkx=1.11=py35_0
- notebook=5.2.2=py35_1
- numexpr=2.6.2=py35_1
- numpy=1.13.3=py35_blas_openblas_201
- numpydoc=0.7.0=py35_0
- obspy=1.0.3=py35_1
- olefile=0.44=py35_0
- openblas=0.2.20=6
- openjpeg=2.1.2=3
- openpyxl=2.5.0a2=py35_0
- openssl=1.0.2m=0
- owslib=0.15.0=py_0
- pandas=0.21.0=py35_0
- pandoc=2.0.4=0
- pandocfilters=1.4.1=py35_0
- pango=1.40.4=0
- paramiko=2.3.1=py_0
- patsy=0.4.1=py35_0
- pcre=8.39=0
- pexpect=4.3.0=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.3.0=py35_1
- pip=9.0.1=py35_0
- pixman=0.34.0=1
- poppler=0.61.1=1
- poppler-data=0.4.8=0
- proj4=4.9.3=5
- prompt_toolkit=1.0.15=py35_0
- psutil=5.4.0=py35_0
- ptyprocess=0.5.2=py35_0
- py=1.5.2=py_0
- pyasn1=0.3.7=py_0
- pycodestyle=2.3.1=py35_0
- pycparser=2.18=py35_0
- pycrypto=2.6.1=py35_1
- pyepsg=0.3.2=py35_0
- pyflakes=1.6.0=py35_0
- pygments=2.2.0=py35_0
- pylint=1.7.1=py35_0
- pynacl=1.1.2=py35_0
- pyopenssl=17.4.0=py35_0
- pyparsing=2.2.0=py35_0
- pyproj=1.9.5.1=py35_0
- pyqt=4.11.4=py35_2
- pyshp=1.2.12=py_0
- pysocks=1.6.7=py35_0
- pytest=3.2.5=py35_0
- pytest-cov=2.5.1=py35_0
- python=3.5.4=1
- python-dateutil=2.6.1=py35_0
- pytz=2017.3=py_2
- pywavelets=0.5.2=py35_1
- pyzmq=16.0.2=py35_2
- qt=4.8.7=7
- qtawesome=0.4.4=py35_0
- qtconsole=4.3.1=py35_0
- qtpy=1.3.1=py35_0
- rasterio=0.36.0=py35_2
- readline=6.2=0
- requests=2.18.4=py35_1
- rope=0.10.7=py35_0
- s3transfer=0.1.11=py35_0
- scikit-image=0.13.0=py35_3
- scipy=1.0.0=py35_blas_openblas_201
- seaborn=0.8.1=py35_0
- setuptools=38.2.4=py35_0
- shapely=1.6.2=py35_1
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- snowballstemmer=1.2.1=py35_0
- snuggs=1.4.1=py35_0
- sphinx=1.6.5=py35_0
- sphinxcontrib-websupport=1.0.1=py35_0
- spyder=3.2.4=py35_0
- sqlalchemy=1.1.13=py35_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=py35_0
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- toolz=0.8.2=py_2
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- typing=3.6.2=py35_0
- urllib3=1.22=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.8=py35_0
- wrapt=1.10.11=py35_0
- xerces-c=3.2.0=0
- xlrd=1.0.0=py35_1
- xlsxwriter=0.9.8=py35_0
- xlwt=1.2.0=py35_0
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- bcrypt=3.1.4=py35ha35c455_0
- configobj=5.0.6=py35_0
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran=3.0.0=1
- util-linux=2.21=0
- nose==1.3.7
- mock==2.0.0
- pbr==3.1.1
- codecov==2.0.9
- commonmark==0.7.3
- dask==0.16.0
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - sphinx-argparse==0.2.1
  - ./libcomcat.zip
  - ./mapio.zip
  - ./impact-utils.zip

